---
# tasks file for packages
#- name: Gathering facts
#  setup:

#- debug: var=ansible_facts['os_family']
#
#- debug: var=ansible_facts.os_family
#
#- debug: var=ansible_os_family


- import_tasks: linux.yml
  when: ansible_os_family == 'Archlinux'
- import_tasks: linux.yml
  when: ansible_os_family == 'Debian'
- import_tasks: windows.yml
  when: ansible_os_family == 'Windows'
#- import_tasks: mac.yml
#  when: ansible_os_family == 'Darwin'